#!/usr/bin/env bash
# Shared helpers for infra/aws operator scripts.
set -euo pipefail

AWS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "${AWS_ROOT}/../.." && pwd)"
export AWS_ROOT REPO_ROOT

# Prefer pip --user ansible-core over apt ansible 2.10 (incompatible with Jinja2 3.x).
export PATH="${HOME}/.local/bin:/usr/local/bin:${PATH}"

TF_BOOTSTRAP="${AWS_ROOT}/terraform/bootstrap"
TF_FLEET="${AWS_ROOT}/terraform/fleet"
ANSIBLE_DIR="${AWS_ROOT}/ansible"
SCRIPTS_DIR="${AWS_ROOT}/scripts"
EXPERIMENTS_DIR="${REPO_ROOT}/experiments"

# /mnt/<drive> (WSL DrvFS) is world-writable, so Ansible ignores ansible.cfg in-tree.
# Force config + host-key policy via env so configure/qualify/launch work from /mnt/f.
export ANSIBLE_CONFIG="${ANSIBLE_DIR}/ansible.cfg"
export ANSIBLE_HOST_KEY_CHECKING=False
export ANSIBLE_ROLES_PATH="${ANSIBLE_DIR}/roles"

# Terraform writes these by default (see terraform/fleet/variables.tf).
INVENTORY_INI="${ANSIBLE_DIR}/inventory.ini"
INVENTORY_YML="${ANSIBLE_DIR}/inventory/hosts.yml"
FLEET_JSON="${ANSIBLE_DIR}/fleet.json"
# Written by infra-apply so finish/destroy can re-supply required TF vars.
CAMPAIGN_ENV="${AWS_ROOT}/.campaign.env"

DEFAULT_REGION="${AWS_REGION:-eu-north-1}"
DEFAULT_WORKERS="${WORKERS:-8}"
DEFAULT_TOTAL_TRIALS="${TOTAL_TRIALS:-900}"
DEFAULT_CONFIG="${CONFIG:-experiments/configs/full.yaml}"
WATCH_INTERVAL_SEC="${WATCH_INTERVAL_SEC:-300}"

die() { echo "error: $*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

# apt ansible 2.10 + pip Jinja2 3.x breaks filters (|bool, |default, …) mid-playbook.
require_ansible() {
  require_cmd ansible-playbook
  local ver major minor
  ver="$(ansible-playbook --version 2>/dev/null | head -1 || true)"
  # "ansible-playbook [core 2.17.14]" or "ansible-playbook 2.10.8"
  if [[ "${ver}" =~ core\ ([0-9]+)\.([0-9]+) ]]; then
    major="${BASH_REMATCH[1]}"
    minor="${BASH_REMATCH[2]}"
  elif [[ "${ver}" =~ ([0-9]+)\.([0-9]+) ]]; then
    major="${BASH_REMATCH[1]}"
    minor="${BASH_REMATCH[2]}"
  else
    die "cannot parse ansible-playbook version from: ${ver}"
  fi
  if [[ "${major}" -lt 2 ]] || { [[ "${major}" -eq 2 ]] && [[ "${minor}" -lt 14 ]]; }; then
    die "ansible-playbook too old (${ver}). Install: pip3 install --user 'ansible-core>=2.15,<2.18' and ensure ~/.local/bin is on PATH (ahead of /usr/bin)."
  fi
  echo "ansible: $(command -v ansible-playbook) (${ver})"
}

# Load CAMPAIGN_ID / SSH_CIDR / … from the last infra-apply.
# Caller-provided environment variables win over the file.
load_campaign_env() {
  if [[ ! -f "${CAMPAIGN_ENV}" ]]; then
    return 0
  fi
  local _cid="${CAMPAIGN_ID-}" _cidr="${SSH_CIDR-}" _key="${SSH_PUBLIC_KEY-}"
  local _bucket="${RESULTS_BUCKET-}" _region="${AWS_REGION-}"
  set -a
  # shellcheck disable=SC1090
  source "${CAMPAIGN_ENV}"
  set +a
  [[ -n "${_cid}" ]] && CAMPAIGN_ID="${_cid}"
  [[ -n "${_cidr}" ]] && SSH_CIDR="${_cidr}"
  [[ -n "${_key}" ]] && SSH_PUBLIC_KEY="${_key}"
  [[ -n "${_bucket}" ]] && RESULTS_BUCKET="${_bucket}"
  [[ -n "${_region}" ]] && AWS_REGION="${_region}"
}

write_campaign_env() {
  local id="${1:?campaign id}"
  local cidr="${2:?ssh cidr}"
  local pubkey="${3:?ssh public key}"
  local bucket="${4:?results bucket}"
  local region="${5:?aws region}"
  umask 077
  cat >"${CAMPAIGN_ENV}" <<EOF
# Generated by infra-apply — do not commit. Sourced by finish/infra-destroy.
CAMPAIGN_ID=${id}
SSH_CIDR=${cidr}
SSH_PUBLIC_KEY=$(printf '%q' "${pubkey}")
RESULTS_BUCKET=${bucket}
AWS_REGION=${region}
EOF
}

resolve_inventory() {
  if [[ -f "${INVENTORY_INI}" ]]; then
    echo "${INVENTORY_INI}"
  elif [[ -f "${INVENTORY_YML}" ]]; then
    echo "${INVENTORY_YML}"
  else
    die "no inventory found (expected ${INVENTORY_INI} or ${INVENTORY_YML}; run make infra-apply first)"
  fi
}

require_fleet_json() {
  [[ -f "${FLEET_JSON}" ]] || die "missing ${FLEET_JSON} (run make infra-apply)"
}

campaign_id() {
  if [[ -n "${CAMPAIGN_ID:-}" ]]; then
    echo "${CAMPAIGN_ID}"
    return
  fi
  if [[ -f "${FLEET_JSON}" ]]; then
    python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["campaign_id"])' "${FLEET_JSON}"
    return
  fi
  die "set CAMPAIGN_ID=… or run make infra-apply so fleet.json exists"
}

results_bucket() {
  if [[ -n "${RESULTS_BUCKET:-}" ]]; then
    echo "${RESULTS_BUCKET}"
    return
  fi
  if [[ -f "${FLEET_JSON}" ]]; then
    python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["results_bucket"])' "${FLEET_JSON}"
    return
  fi
  # Fallback: bootstrap naming convention
  local acct
  acct="$(aws sts get-caller-identity --query Account --output text)"
  echo "ii2202-experiments-${acct}"
}

# Make's `export AWS_REGION` can pass an empty value into recipes, which overrides
# ~/.aws/config and yields Invalid endpoint: https://s3..amazonaws.com.
ensure_aws_region() {
  load_campaign_env
  if [[ -z "${AWS_REGION:-}" ]]; then
    if [[ -f "${FLEET_JSON}" ]]; then
      AWS_REGION="$(python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); print(d.get("region") or d.get("aws_region") or "")' "${FLEET_JSON}")"
    fi
  fi
  if [[ -z "${AWS_REGION:-}" ]]; then
    AWS_REGION="${DEFAULT_REGION}"
  fi
  export AWS_REGION
  export AWS_DEFAULT_REGION="${AWS_REGION}"
}

campaign_local_dir() {
  local id
  id="$(campaign_id)"
  echo "${REPO_ROOT}/results/campaigns/${id}"
}

s3_campaign_uri() {
  local id bucket
  id="$(campaign_id)"
  bucket="$(results_bucket)"
  echo "s3://${bucket}/campaigns/${id}"
}

chunk_size() {
  local total workers
  total="${TOTAL_TRIALS:-$DEFAULT_TOTAL_TRIALS}"
  workers="${WORKERS:-$DEFAULT_WORKERS}"
  python3 -c "import math; print(math.ceil(int('${total}') / int('${workers}')))"
}

config_rel_for_worker() {
  # Worker checkout has experiments/ as cwd; strip experiments/ prefix if present.
  local cfg="${CONFIG:-$DEFAULT_CONFIG}"
  if [[ "${cfg}" == experiments/* ]]; then
    echo "${cfg#experiments/}"
  else
    echo "${cfg}"
  fi
}

ensure_harness_bin() {
  if [[ ! -x "${EXPERIMENTS_DIR}/bin/harness" ]]; then
    echo "building local harness…"
    require_cmd go
    (
      cd "${EXPERIMENTS_DIR}"
      mkdir -p bin
      go build -o bin/harness ./cmd/harness
    )
  fi
}
